metadata:
  version: '1.0'
  last_updated: '2025-07-31T20:18:17.312589'
exploits:
- id: POC-001
  name: Example HTTP PoC
  description: A basic example PoC for an HTTP service.
  type: poc
  target:
    service: http
    cve: N/A
  parameters:
    target_host:
      type: string
      required: true
      description: Target hostname or IP
    target_port:
      type: integer
      required: false
      default: 80
      description: Target port
  execution:
    handler: builtin_poc_example_http
- id: MSF-EXPLOIT-123
  name: Metasploit Example Exploit
  description: Launches a Metasploit exploit module.
  type: metasploit
  target:
    service: ssh
    cve: CVE-XXXX-YYYY
  parameters:
    target_host:
      type: string
      required: true
    target_port:
      type: integer
      required: false
      default: 22
    username:
      type: string
      required: false
      default: root
    password:
      type: string
      required: false
      default: password
  execution:
    msf_module: exploit/linux/ssh/example_exploit
    msf_options: RHOSTS {target_host} RPORT {target_port} USERNAME {username} PASSWORD
      {password}
